### ISSUE TITLE
HeapPriorityQueue doesn't let one iterate in unsorted order

### ISSUE THREAD

**Issue by sortie** [dart-lang/collection#140]
My code has several huge priority queues using `HeapPriorityQueue`, where it occasionally needs to consider all the elements in the queue where the order doesn't matter (e.g. to tally up how long it will take to process the queue, or to consider all the items and move a few to another queue if circumstances changes).

However, `HeapPriorityQueue` only offers `toList()` and `toSet()` for this purpose. However, they spend O(nlogn) to sort the queue (and I need a linear time algorithm) and duplicates the data structure (I just need constant memory). The only way to iterate the queue in linear time in unsorted order is to use `removeAll()`, however it is destructive.

The `HeapPriorityQueue` internally just uses a list to manage the data structure, which is what is returned by  `removeAll()`. It could easily gain a `Iterable<E> get unsorted` getter or something that returns the backing data structure with the appropriate concurrent modification protections.

This is probably a breaking change and needs a major version bump in case anyone implemented `HeapPriorityQueue`.

I'm currently working around the issue associating each priority queue with a `Set` in my mod, however it duplicates the amount of memory spent on the queues.

**Comment by lrhn** [comment]
Adding a member to an implementation class is not a breaking change, so we can add it to `HeapPriorityQueue`. It's potentially breaking to add it to the interface `PriorityQueue`, since that is intended for general use, and someone might be implementing it.

It's somewhat annoying to add an operation which is not general to all `PriorityQueue`s, but since some priority queues could easily keep objects in priority order all the time, an `unorderedElements` iterable getter wouldn't make sense for them. 
The class interface itself does not implement `Iterable`, so we haven't promised any way to access elements other than the "highest priority" one, and some priority queues might not even be able to do so (unlikely, but possible).
So, adding just to `HeapPriorityQueue` can be reasonable.

If we do it, I'd suggest `Iterable<E> get unorderedElements;`, documented to say that you must not modify the queue during iteration, and that you must not modify the elements to change their priority (in that case, do a `removeAll` followed by a rebuild).

**Comment by lrhn** [comment]
I've added `toUnorderedList` to `PriorityQueue`. Let's see if anyone implements it.

**Comment by sortie** [comment]
The `toUnorderedList` implementation solves the runtime complexity issue by reducing it from O(nlogn) to O(n). However, it still uses O(n) time and memory to duplicate the queue. It looks like this feature got bundled with null safety so my service can't use it until null safety is released.

The `toUnorderedList` design seems a bit suboptimal for performance. My ideal interface would be something like `Iterable<E> get unordered` (or maybe an `Iterator<E>`):

* It allows returning the raw backing data structure with the appropriate concurrent modification protections, which uses constant memory, unlike `toUnorderedList` that spends linear memory.
* The runtime to iterate is split uniformly between entries, unlike `toUnorderedList` that has a big up front cost for large data structures.
* Different implementations of PriorityQueue might use a different backing data structure which might not be a list.

In my case, I have very big priority lists with many millions of entries, and doing operations to consider all the elements (in no particular order) is very expensive (and I try to do it as little as possible). The big up front allocation can create a big delay where I can't use async boundaries to let other code paths remain responsive. Being able to iterate the backing data structure with no duplication makes this operation cheaper.

Make no mistake, `toUnorderedList` is an improvement, but isn't really more efficient than my code that maintains a set with all the entries in the queue, so the memory is already duplicated, and that set doesn't need to be rebuilt each time the queue is iterated.

**Comment by lrhn** [comment]
So a better API would be `Iterable<T> removeAll()` which clears the queue and provides an iterable of the elements.
It's not a list, but that also means it doesn't have to be copied. It would probably be possible to use `CastIterable` as wrapper, since it needs a wrapper.

I'll think about this again, we haven't released it yet.

**Comment by natebosch** [comment]
> I'll think about this again, we haven't released it yet.

I missed this comment before I published. It's release, but with a prerelease `-nullsafety` version.

Do we need to consider quickly reverting that to avoid it getting picked up by flutter?

cc @jakemac53

**Comment by lrhn** [comment]
Probably not needed. We can add `removeAllUnordered` and keep `toUnorderedList` as well.

**Comment by sortie** [comment]
No, I do not need a destructive iterator. That means I need to pay `O(nlogn)` to rebuild the queue again. Besides `removeAll()` is already efficient and returns the elements in no particular order.

I just want to non-destructively iterate the elements in the queue in no particular order in linear time with constant memory use.

**Comment by lrhn** [comment]
Have now landed `unorderedElements` in https://github.com/dart-lang/collection/commit/b836c70a7438d444be9a26c007ca1c19a53c9d20.
