### ISSUE TITLE
Add type assertion wrappers

### ISSUE THREAD

**Issue by nex3** [dart-lang/collection#25]
As the ecosystem moves to strong mode, we'll no longer be able to treat collections without generic types as though they had those types—stuff like `list as List<String>` will fail at runtime if the reified generic type doesn't match up. This can be avoided by writing stuff like `new List<String>.from(list)`, but that involves copying the list—it's not as efficient as it could be, and it won't work at all if the user is relying on being able to see changes in the underlying list.

To fix this, we should provide properly-typed wrapper classes that assert the types of all values they returns from the underlying object. These could either be seperate types (`CoercingListView`? `AssertingListView`?) or constructors on the existing delegating types (`new DelegatingList.coerce()`? `new DelegatingList.assertType()`?).

**Comment by leafpetersen** [comment]
@skybrian had an issue in a CL recently that this might help with.

**Comment by skybrian** [comment]
I don't think it would help for protobuf, since we need to support subtypes of List. (Protobuf uses the PbList type, and we eventually want to support an ObservablePbList type.)

Protobuf needs some kind of dynamic constructor call where the list type and the item type are both decided at runtime. This can be modeled by passing in a factory class, but then we need to define a subtype for every repeated field, so it increases generated code bloat.

A type assertion wrapper might be useful for other reasons though.
