### ISSUE TITLE
The reason why elementAtOrNull doesn't allow negative numbers

### ISSUE THREAD

**Issue by bobekos** [dart-lang/collection#272]
Hi guys,

i wonder why elementAtOrNull throws a exception when we passed negative number instead of just return null.

So why it is like this:
```
E? elementAtOrNull(int index) => (index < length) ? this[index] : null;
```

instead of this:
```
E? elementAtOrNull(int index) => (index > -1 && index < length) ? this[index] : null;
```

I saw the #217 merge request and also there i can't see any reason to avoid this check.

**Comment by lrhn** [comment]
The behavior matches `elementAt`, which also requires a non-negative value.

You know for certain that an iterable or list never has an element with a negative index, because indices count up from zero. There is no reason to even ask `elementAt` or `elementAtOrNull`, the result is a given.

You don't know how many elements an iterable has without iterating, so you can't check the index for being too large ahead of time, but you can check it for being negative. So you should.

Throwing if you pass in a negative index can catch errors. If you accidentally do some mis-computation, giving you an early and visible error is better than silently pretending that you probably meant to always ask for a `null` in an inconvenient way. That can propagate into other errors later, say you do `iterable.skip(start).elementAtOrNull(start - end)` (should have been `end - start`) and it returning `null` makes you go on assuming that there are no elements after `end`.
Instead it throws, telling you immediately that you made a mistake.

**Comment by lrhn** [comment]
Your approach is also valid, but it's generally not the way we've designed the Dart APIs.

When we've allowed an "or null" result, it's for properties that you cannot (easily) check before trying, where you would not be able to avoid the throwing of the throwing variant by pre-checking the inputs, or not significantly cheaper than going the computation anyway.

For `elementAt`, there are two ways to fail: 
- by passing an argument that is not a valid _index_ at all, meaning a negative number, which you can easily check, or
- by passing a valid index which is after the end of the `Iterable`. There is no general way to know that without iterating the entire `Iterable`, and then you might as well return the element of you find it along the way. 

Those two error cases are significantly different, and conflating them by returning `null` in either case, will maker it easier to hide real mistakes, while not really giving you anything that you couldn't also get from a simple `index < 0 ? null : ` prefix to the call.

Or, in other words, the goal is not to provide an API which cannot throw. That's never a goal that we're aiming for in Dart libraries Rather, making errors visible is a goal, and hiding obvious errors is counter to that goal.

The goal here is to provide a way to do something on one pass, which would otherwise require two passes to do safely, as `index >= it.length ? null : it.elementAt(index)`.
Nothing more, nothing less.

Accepting a negative index, which is known to never be valid, isn't useful for that, because according that error doesn't require any iteration.
