### ISSUE TITLE
`different` method extension

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/collection#293]
Sometimes I find myself having to do some _sql-like_ queries inside my iterables. 

Mostly, they are usually solved by: `.map((obj) => obj.property).toSet()` then processing this result.

Consider adding a method that does this by default.

PS: Maybe add something similar to the `count` SQL option, where this could be used and return only the length. If you like this idea, I can create another issue for it.

**Comment by lrhn** [comment]
There is a limit to how many specialized methods we want to add to iterables, when there are already ways to achieve the goal using the existing primitives.

We could go all in, and add every conceivable combination, each with an optional `map` and `where` in some order, but predicting what people want is hard, and we'd risk creating combinations that are never used, or which hide the real cost of an operation.

Since anyone can write an extension method like 
```dart
extension <E> on Iterable<E> {
  int countDistinctOf<R>(R Function(E) convert) =>
    this.map(convert).toSet().length;
}
```
it's likely better that they do so.
Rather than me trying to guess whether they also want to control the equality used by the set, and someone else using a function like that without realizing that it uses linear memory.
