### ISSUE TITLE
Add `Map<int, Object?>.asList()` method

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/collection#310]
In Dart, there already is a method for `List<E>`s that allows us to use them as `Map<int, E>`. It is called `asMap`.

I propose that we could add a way to revert back from `Map<int, E>` to `List<E>`.

```dart
class _MapToList<T extends Object?> with ListMixin<T> implements List<T> {
  _MapToList(this.baseMap);

  final Map<int, T> baseMap;

  @override
  int get length => baseMap.length;

  @override
  set length(int newLength) {
    if (newLength == length) return;
    if (newLength < 0) throw RangeError.value(newLength);
    if (newLength > baseMap.length) {
      for (int i = baseMap.length; i < newLength; i++) {
        baseMap[i] = null as T;
      }
    } else {
      for (int i = baseMap.length - 1; i >= newLength; i--) {
        baseMap.remove(i);
      }
    }
  }

  @override
  T operator [](int index) {
    if (index < 0 || index >= baseMap.length) {
      throw RangeError.range(
        index,
        0,
        length - 1,
        'index',
        'index out of range',
      );
    }
    return baseMap[index]!;
  }

  @override
  void operator []=(int index, T value) => baseMap[index] = value;
}

extension AsListExt<T extends Object?> on Map<int, T> {
  List<T> asList() => _MapToList<T>(this);
}
```

**Comment by FMorschel** [comment]
I'm only suggesting this change because I saw that there is already a `whereNotNull` method added by this package where the extension is added only to lists that can have nullable elements. So I figured this could be a specific case like that.

**Comment by lrhn** [comment]
I don't think the "map as list" operation is as natural as the other direction.

Every list defines a mapping from a set of integers to elements. Those integers area always consecutive and starting from zero, but maps don't care about that.

Not every map with integer keys represent a list. Only those where the keys happen to be consecutive integers starting at zero. 
For example, it's possible for such a map to have a length of 10, but no keys in the 0..9 range. They could be in the millions, they could be negative.

The code here doesn't try to verify that the map could be a list. 
Which means that setting the list `length` could easily end up not changing the `length` getter value anyway,
because it doesn't remove anything. Or it might overwrite existing fields. Fx `print(({1: 42}.asList()..length = 2).length)` prints 1.

Doing the validation would be about as expensive as actually creating a new list, and then I'd still worry that someone might change the map afterwards.

So, all in all, lists make adequate unmodifiable maps, but maps make bad lists.
