### ISSUE TITLE
mergeSort fails when static type of a list does not match a runtime type 

### ISSUE THREAD

**Issue by iinozemtsev** [dart-lang/collection#317]
https://dartpad.dev/?id=f9535fca683721dd5eb4416e364cc5df

```dart
import 'package:collection/collection.dart';
import 'dart:math';

void main() {
  final rnd = Random(9092);
  final ints = List.generate(1000, (i) => rnd.nextInt(10000));
  mergeSort<num>(ints);
  print(ints);
}
```

[scratchSpace](https://github.com/dart-lang/collection/blob/d27bfaf7994ee690be6ed424b8ee288c7aa672f6/lib/src/algorithms.dart#L235) is created with a function type argument, and then [setRange](https://github.com/dart-lang/collection/blob/d27bfaf7994ee690be6ed424b8ee288c7aa672f6/lib/src/algorithms.dart#L398) fails, because runtime element types don't match.

**Comment by iinozemtsev** [comment]
@natebosch @devoncarew could you please take a look?

**Comment by eernstg** [comment]
Looks like `mergeSort` uses a `scratchSpace` which is a `List<E>` (type argument taken from the type argument of `mergeSort`, often by inference or manually also the statically known type argument of the list-being-sorted).

I haven't tried it in detail, but it looks like we'd simply need to ensure that the `scratchSpace` has the same type argument as the `elements`:

```dart
  // `src/algorithms.dart`, line 235:
  var scratchSpace = List<E>.filled(secondLength, elements[start]);

  // Could be the following, except that this would be too slow:
  var scratchSpace = elements.take(0).toList();
  var startElement = elements[start];
  for (int i = 0; i < secondLength; ++i) scratchSpace.add(startElement);
```

**Comment by yanok** [comment]
```dart
var scratchSpace = elements.take(secondLength).map((_) => elements[start]).toList()
```

maybe?

**Comment by rakudrama** [comment]
> Looks like `mergeSort` uses a `scratchSpace` which is a `List<E>` (type argument taken from the type argument of `mergeSort`, often by inference or manually also the statically known type argument of the list-being-sorted).
> 
> I haven't tried it in detail, but it looks like we'd simply need to ensure that the `scratchSpace` has the same type argument as the `elements`:
> 
> ```dart
>   // `src/algorithms.dart`, line 235:
>   var scratchSpace = List<E>.filled(secondLength, elements[start]);
> 
>   // Could be the following, except that this would be too slow:
>   var scratchSpace = elements.take(0).toList();
>   var startElement = elements[start];
>   for (int i = 0; i < secondLength; ++i) scratchSpace.add(startElement);
> ```

There are problems to using `toList` like this:
- Merge sort copies elements from A to B and from B to A, so _invariance_ is required. `toList` does not have to return a list with exactly the right element type, just a subtype.
- It leaves the efficiency of `mergeSort` at the mercy of the implementation type of `.take(0).toList()`. In the original code`List.filled` can be reasonably expected to return a `List` that is a 'fixed length system list' with fast indexing. Who knows what implementation `toList` returns? Even if it is of uniform implementation type, can the optimizing compilers figure it out? If not, all the indexing is done via dispatched calls.

I think the type error in `_merge` can be repaired by writing a copy loop instead of `setRange`. In effect, the parametric covariance check happens for each element rather than the collection.

Heretical opinion: `mergeSort` should always copy the original `List` into a scratch space that is 1.5x larger than the original [start, end) slice, perform all the sorting in the scratch space, and copy back at the end (if there was any actual change). This way, the inner loops of the algorithm can be guaranteed to be operating of a fixed length system list to avoid the dispatched call, and the code can be written so that the compiler can see that the list assignments are all essentially `a[i] = a[j]` and avoid the parametric covariant checks by local invariance reasoning. Does this matter enough with the `keyOf` and `compare` calls? Maybe not.

**Comment by natebosch** [comment]
We have a package which could solve this, but it cheats and uses capabilities the language normally doesn't have.
https://pub.dev/documentation/dart_internal/latest/extract_type_arguments/extractIterableTypeArgument.html

I don't think we want to spread usage of that package unless we are fairly confident that we are going to add a language level capability to replace it eventually, such as type patterns. https://github.com/dart-lang/language/issues/170

**Comment by eernstg** [comment]
@rakudrama wrote:
> ... _invariance_ is required. `toList` does not have to return a list with exactly the right element type, just a subtype.

Right, the member signature and specified behavior of `toList` in `Iterable<E>` allows it to return a `List<S>` for any `S <: E` that allows the list to contain the given elements. The implementation shown [here](https://api.dart.dev/stable/3.1.5/dart-core/Iterable/toList.html) will return a `List<E>`, but any subtype could override that.

So we don't have (and inherently can't have) any tool which is guaranteed to yield a fresh list whose run-time type implements `List<E>` from a given `List<E>` (that is, we don't have and can't write a `cloneFilled` method).

In any case, we could provide something like `extractIterableTypeArgument`, and I was just making the point that we'd need invariance (dynamically: From a list whose run-time type implements `List<E>` we want a fresh list whose run-time type implements `List<E>`, not just some subtype or supertype of that, and not just something based on the static types), and `take(0).toList()` will do that in practice. ;-)

**Comment by natebosch** [comment]
> and inherently can't have

Would type patterns enable this?

**Comment by eernstg** [comment]
> Would type patterns enable this?

Yes. Type patterns is a meta-proposal in the sense that the basic idea can be applied to static types as well as run-time types, in various ways. One typical example would be that we use type patterns to bind a type variable to the run-time value of a type parameter at a given type, and that particular feature would support the following:

```dart
void main() {
  List<num> xs = <int>[1];
  if (xs is List<final X>) { // `X` is in scope here, the value is `int`.
    var newList = List<X>.filled(someLength, xs.first);
  }
}
```

**Comment by lrhn** [comment]
I'd probably just trust `.toList()` to do the right thing here. 

The `Iterable.toList` is under-specified, but it *should* return a list with exactly the same element type as the original iterable. It's a mutable list, so the client can expect to set or add more elements. Returning a list of a subtype of the actual element type isn't safe for that, so it shouldn't ever happen.

I expect `.take(secondLength).toList(growable: false)` is more efficient than `.take(0).toList()` followed by some way of growing it to the correct length.
The copying will probably be wasted, since we already have the elements in that order, but we need to be writing *something* into list to grow it. 
(An efficient `ListTakeIterable.toList()` could use a mem-copy to initialize a newly allocated list, but it probably doesn't.)
