### ISSUE TITLE
List.replaceAll

### ISSUE THREAD

**Issue by fredspizza** [dart-lang/collection#329]
Has anyone considered a replaceAll method on List, where the contents of an existing list are replaced by the contents of an Iterable? It would be like addAll() with a clear() step first.

I've created a pretty simple extension to do it myself - not clear if this would be more broadly useful, but thought I'd drop it here.

```dart
// Copyright (c) 2018, the Dart project authors.  Please see the AUTHORS file
// for details. All rights reserved. Use of this source code is governed by a
// BSD-style license that can be found in the LICENSE file.
extension ListExtension<T> on List<T> {
  /// Replaces all the items in the list with all the objects in [iterable].
  /// 
  /// The size of the original list will now be equal to [iterable].length.
  /// The list must be modifiable.
  /// 
  /// ```dart
  /// final numbers = [1, 2, 3];
  /// numbers.replaceAll([4, 5]);
  /// print(numbers); // [4, 5]
  /// ```
  void replaceAll(Iterable<T> iterable) {
    clear();
    addAll(iterable); 
  }
}
```

**Comment by rakudrama** [comment]
It does seem rather hard to simply 'assign' the values of one List into another.
Especially in a general way that works for fixed-length Lists as well as growable Lists with different numbers of elements.

The name `replaceAll` might be confusing to some because `String.replaceAll` does something completely different.

I personally would find a simple extension of limited utility because I can use a cascade to call `clear()` and `addAll()`:
```dart
numbers..clear()..addAll([4, 5]);
```
It might be better to use [`List.replaceRange`](https://api.flutter.dev/flutter/dart-core/List/replaceRange.html) 
```dart
numbers.replaceRange(0, numbers.length, [4, 5])
```
either directly, or in your extension, since the documentation says that it _may_ be more efficient (it might be able to reuse the backing store for the growable List).

**Comment by lrhn** [comment]
I don't see a big demand for reopening the content of one list with the content of another, when the alternatives could be either just pointing to the second list directly, or using `..clear()..addAll(...)` or `replaceRange`.

That is, don't expect it to be ordered often enough that the alternatives are not good enough.
