### ISSUE TITLE
Add changelog entries for 1.14.3 + 1.14.2

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/collection#61]
Please?

@jmesserly @lrhn

**Comment by jmesserly** [comment]
there was no user-visible change in 1.14.3, it has a fix for a strong mode error in an implementation class (and that error isn't visible yet, because the Analyzer fix hasn't landed).

IDK what to say. "fixes a strong mode error in an implementation class"? the only commit is https://github.com/dart-lang/collection/commit/a15382f5c5b1dbf5c1e338b727dbc78755caed0c

**Comment by kevmoo** [comment]
That's fine. It's just weird to see blankness.

Why release if there are no user facing changes?

**Comment by jmesserly** [comment]
> Why release if there are no user facing changes?

because DDC builds will stop working on the new SDK if people don't update, and I need to pull this version (via DEPS) into Dart SDK repo, and into our internal codebase

**Comment by kevmoo** [comment]
Ah! so there are user-facing changes. Just for folks using DDC. That's fine to put in the changelog 😄

**Comment by nex3** [comment]
All releases should have changelog entries, even if those entries just say "No user-visible changes."
