### ISSUE TITLE
QueueList's cast and retype do not adhere to the List methods' documentation

### ISSUE THREAD

**Issue by srawlins** [dart-lang/collection#87]
I'd like to say that QueueList's `cast` and `retype` do not adhere to the _contract_ laid out by `List.cast` and `List.retype` but that may be up for debate. In any case, `List.cast`'s documentation says:

> Returns a view of this list as a list of `R` instances, if necessary.

`List.retype`'s documentation says, similarly:

> Returns a view of this list as a list of `R` instances.

(Ignoring for now what "if necessary" must mean...) I believe it is intended that the return value be *the same list* (just a different view of it), **not** a new list. For example, let's play with `List`:

```dart
void main() {
  var a = new List<num>()..addAll([1,2,3]);
  var b = a.retype<int>();
  b.add(4); // add 4 to the view.
  a.add(5); // add 5 to the original.
  b.remove(3); // remove 3 from the view.
  print('a: $a'); //=> [1, 2, 4, 5]
  print('b: $b'); //=> [1, 2, 4, 5]
}
```

They are the same list. Now let's do the same for QueueList:

```dart
import 'package:collection/collection.dart';

void main() {
  var c = new QueueList<num>()..addAll([1,2,3]);
  var d = c.retype<int>();
  d.add(4);
  print('c: $c'); //=> {1, 2, 3} // Not the same list!
  print('d: $d'); //=> {1, 2, 3, null, null, null, null, null, 4} // Duck?
  c.add(5);
  print('c: $c'); //=> {1, 2, 3, 5}
  print('d: $d'); //=> {1, 2, 3, null, null, null, null, null, 4}
}
```

I have not checked the other `cast` and `retype` implementations yet, but when I do, I presume I'll just add on to this bug, rather than filing a bug for each class.

**Comment by matanlurey** [comment]
> I believe it is intended that the return value be *the same list* (just a different view of it), **not** a new list.

I don't think so (@leafpetersen @lrhn), even though I wish that was the case - I think `.cast` _tries_ to re-use the same list, and basically invokes `.retype` if not possible, making this OK. 

I.e. this is just a convenience for calling `List.castFrom`:

https://github.com/dart-lang/sdk/blob/f1ebe2bd5cfcb6b522e5b4fd406cdabb1a2d2091/sdk/lib/collection/list.dart#L332-L335

Let's look at the implementation of `DoubleLinkedQueue.cast`:

https://github.com/dart-lang/sdk/blob/f1ebe2bd5cfcb6b522e5b4fd406cdabb1a2d2091/sdk/lib/collection/queue.dart#L359-L362

Unfortunately there is no way in Dart to really "re-type" something, so unlike Dart 1's `as List<String>`, `list.cast<String>()` may return a new list if necessary to fulfill that cast.

**Comment by lrhn** [comment]
Both `cast` or `retype` *are* really intended to return a view of the original collection, one that also forwards mutating methods. The "if necessary" means that `cast` returns the original list if it already implements the desired interface, possibly by implementing a subtype, where `retype` always wraps so the return type is exact.

The `QueueList` class has the extra issue of needing to implement both `List.cast` and `Queue.cast`, so it needs to return something that is both a `List` and a `Queue`. I have a class ready for that in the private parts of the SDK, because one of the plans for Dart 2 was to make `ListQueue` implement `List` as well, but that doesn't help this package.

**Comment by matanlurey** [comment]
Let me give this a shot, thanks @srawlins and @lrhn.
